# Generated by Django 3.0.3 on 2020-06-25 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='String, max. 1200 char', max_length=1200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('shared_post',
                 models.ForeignKey(blank=True, help_text='ID of post that this post is sharing', null=True,
                                   on_delete=django.db.models.deletion.CASCADE, related_name='posts_sharing_me',
                                   to='post.Post')),
                ('user', models.ForeignKey(help_text='ID of author', on_delete=django.db.models.deletion.CASCADE,
                                           related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
