# Generated by Django 3.0.3 on 2020-07-01 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='List of users who liked this post', related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='shared_post',
            field=models.ForeignKey(blank=True, help_text='ID of shared post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_sharing_me', to='post.Post'),
        ),
    ]
