# Generated by Django 3.0.3 on 2020-07-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200701_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(blank=True, help_text='Shared Link', max_length=1000),
        ),
    ]
