# Generated by Django 3.0.3 on 2020-06-25 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts-images')),
                ('post',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.Post')),
            ],
        ),
    ]
