# Generated by Django 3.0.3 on 2020-07-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200701_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, help_text='Code sent via e-mail', max_length=6),
        ),
    ]
