# Generated by Django 3.0.3 on 2020-06-25 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status',
                 models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P',
                                  max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiver',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received',
                                   to=settings.AUTH_USER_MODEL)),
                ('requester',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_sent',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
